#!/usr/bin/env python

# Cross validates extracted sentences using the training set

# Anshul Sharma (ansharma)

import optparse
import sys
from collections import defaultdict

optparser = optparse.OptionParser()
optparser.add_option("-d", "--data", dest="train", default="data/de", help="Data filename prefix (default=data/de)")
optparser.add_option("-e", "--english", dest="english", default="orig.enu.snt", help="Suffix of English filename (default=orig.enu.snt)")
optparser.add_option("-f", "--foreign", dest="foreign", default="orig.deu.snt", help="Suffix of Foreign filename (default=orig.deu.snt)")
optparser.add_option("-n", "--num_sentences", dest="num_sents", default=sys.maxint, type="int", help="Number of sentences to use for training and alignment")
(opts, _) = optparser.parse_args()
f_data = "%s/%s" % (opts.train, opts.foreign)
e_data = "%s/%s" % (opts.train, opts.english)

